name = "enso_project"
uuid = "92f8d58f-31a9-439a-b05e-792ebdf1e7ff"
authors = ["Lisa", "Beer <lisa.beer@tum.de>", "Andrea Pinke <andrea.pinke@tum.de>"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
